import { randomBytes } from 'node:crypto';
import { mkdir, rm } from 'node:fs/promises';
import { join } from 'node:path';

import { PrismaClient } from '@prisma/client';
import { Queue } from 'bullmq';
import sharp from 'sharp';

import { createAssetCleanupQueue, createBullConnectionOptions } from '@dreamstudio/queue';
import { cleanupAssets, DreamStudioSecretCodec } from '@dreamstudio/storage';

const API_BASE_URL = process.env.DREAMSTUDIO_VERIFY_API_URL ?? 'http://127.0.0.1:3001';
const VERIFY_ORIGIN = process.env.APP_BASE_URL ?? 'http://localhost:3000';
const ADMIN_USERNAME = process.env.INITIAL_ADMIN_USERNAME ?? 'Cherry';
const ADMIN_PASSWORD = process.env.INITIAL_ADMIN_PASSWORD ?? 'DreamStudio';
const USERNAME_A = `m4_user_a_${Date.now()}`;
const USERNAME_B = `m4_user_b_${Date.now()}`;
const PASSWORD = 'DreamStudioM4!';
const LOCAL_STORAGE_ROOT =
  process.env.DREAMSTUDIO_VERIFY_M4_STORAGE_ROOT ?? `/tmp/dreamstudio-m4-${Date.now()}`;

const prisma = new PrismaClient();

interface CookieJar {
  cookie: string;
  csrfToken: string;
}

interface ApiEnvelope<T> {
  success: boolean;
  data?: T;
  error?: {
    code: string;
    message: string;
    details?: unknown;
  };
}

interface AuthPayload {
  user: {
    id: string;
    username: string;
    role: 'user' | 'super_admin';
  };
  csrf_token: string;
}

interface AssetPayload {
  item: {
    id: string;
    kind: 'reference_image' | 'result_image';
    filename: string;
    mime_type: string;
    width: number | null;
    height: number | null;
    download_url: string;
  };
}

interface StorageSettingsPayload {
  driver: 'local' | 's3';
  local_input_path: string;
  local_output_path: string;
  masked_s3_access_key: string | null;
  masked_s3_secret_key: string | null;
}

async function main() {
  await mkdir(LOCAL_STORAGE_ROOT, { recursive: true });
  const admin = await login(ADMIN_USERNAME, ADMIN_PASSWORD);
  const userA = await register(USERNAME_A, PASSWORD);
  const userB = await register(USERNAME_B, PASSWORD);

  const localInputPath = join(LOCAL_STORAGE_ROOT, 'references');
  const localOutputPath = join(LOCAL_STORAGE_ROOT, 'results');
  const settings = await put<StorageSettingsPayload>('/api/v1/admin/storage-settings', admin.jar, {
    driver: 'local',
    local_input_path: localInputPath,
    local_output_path: localOutputPath,
    reference_retention_hours: 1,
    result_retention_hours: 24,
  });
  assert(settings.driver === 'local', 'admin can configure local storage');
  assert(
    settings.masked_s3_access_key === null && settings.masked_s3_secret_key === null,
    'local storage settings response does not include stored S3 secrets',
  );

  const testResult = await post<{ ok: boolean; tested_at: string }>(
    '/api/v1/admin/storage-settings/test',
    admin.jar,
    {},
  );
  assert(testResult.ok, 'admin storage test succeeds');

  const png = await sharp({
    create: {
      width: 8,
      height: 6,
      channels: 4,
      background: '#0f766e',
    },
  })
    .png()
    .toBuffer();

  const uploaded = await uploadReferenceImage(userA.jar, png);
  assert(uploaded.item.kind === 'reference_image', 'reference image upload returns asset');
  assert(
    uploaded.item.width === 8 && uploaded.item.height === 6,
    'upload records image dimensions',
  );
  assert(
    !JSON.stringify(uploaded).includes(localInputPath),
    'asset response does not expose local path',
  );

  const dbAsset = await prisma.asset.findUniqueOrThrow({
    where: {
      id: uploaded.item.id,
    },
  });
  assert(dbAsset.userId === userA.payload.user.id, 'asset is owned by uploading user');
  assert(dbAsset.objectKey !== uploaded.item.filename, 'object key is generated by system');
  assert(!dbAsset.objectKey.includes('sample.png'), 'object key does not reuse original filename');

  const listed = await get<{ items: Array<{ id: string }> }>(
    '/api/v1/assets?kind=reference_image',
    userA.jar,
  );
  assert(
    listed.items.some((asset) => asset.id === uploaded.item.id),
    'owner can list uploaded reference image',
  );

  const download = await fetch(`${API_BASE_URL}${uploaded.item.download_url}`, {
    headers: {
      cookie: userA.jar.cookie,
      accept: 'image/png',
    },
  });
  const downloadBytes = await download.arrayBuffer();
  assert(
    download.ok,
    `owner can download asset via ${uploaded.item.download_url} (${download.status} ${Buffer.from(
      downloadBytes,
    ).toString('utf8')})`,
  );
  assert(
    download.headers.get('content-type')?.startsWith('image/png'),
    'download returns image content type',
  );
  assert(downloadBytes.byteLength > 0, 'download returns bytes');

  await expectFailure(
    get(`/api/v1/assets/${uploaded.item.id}`, userB.jar),
    'cross-user asset detail is rejected',
  );
  await expectFailure(
    del(`/api/v1/assets/${uploaded.item.id}`, userB.jar),
    'cross-user asset delete is rejected',
  );

  const deleted = await del<{ deleted: boolean; physical_deleted: boolean }>(
    `/api/v1/assets/${uploaded.item.id}`,
    userA.jar,
  );
  assert(deleted.deleted, 'owner can soft delete asset');

  const deletedAsset = await prisma.asset.findUniqueOrThrow({
    where: {
      id: uploaded.item.id,
    },
  });
  assert(Boolean(deletedAsset.deletedAt), 'asset deleted_at is set');
  assert(deletedAsset.status !== 'available', 'deleted asset is no longer available');

  const cleanupAsset = await prisma.asset.create({
    data: {
      userId: userA.payload.user.id,
      kind: 'reference_image',
      status: 'available',
      storageDriver: 'local',
      bucket: null,
      objectKey: `references/${userA.payload.user.id}/missing-${randomBytes(4).toString('hex')}.png`,
      filename: 'missing.png',
      mimeType: 'image/png',
      sizeBytes: 10n,
      checksum: 'verify-m4-cleanup',
      expiresAt: new Date(Date.now() - 60_000),
    },
  });
  await enqueueCleanupAndWait();
  const cleaned = await prisma.asset.findUniqueOrThrow({
    where: {
      id: cleanupAsset.id,
    },
  });
  assert(cleaned.cleanedAt, 'cleanup marks expired asset cleaned');

  const cleanupRun = await prisma.cleanupRun.findFirst({
    where: {
      jobType: 'asset-cleanup',
    },
    orderBy: {
      createdAt: 'desc',
    },
  });
  assert(cleanupRun, 'cleanup run is recorded');
  assert(cleanupRun.scannedCount >= 1, 'cleanup run records scanned count');

  const auditCount = await prisma.auditLog.count({
    where: {
      actorUserId: admin.payload.user.id,
      action: {
        in: ['admin_update_storage_settings', 'admin_test_storage_settings'],
      },
    },
  });
  assert(auditCount >= 2, 'storage settings update/test writes audit logs');

  console.log(
    JSON.stringify({
      ok: true,
      checks: [
        'local_storage_settings',
        'storage_test',
        'reference_upload',
        'asset_db_metadata',
        'download',
        'cross_user_404',
        'delete_asset',
        'cleanup_queue',
        'audit_logs',
      ],
    }),
  );
}

async function enqueueCleanupAndWait() {
  const connection = createBullConnectionOptions();
  const queue = createAssetCleanupQueue(connection);
  const marker = new Date();
  try {
    await queue.add('verify-m4-cleanup', {
      job_version: 1,
      asset_kind: 'reference_image',
      before: marker.toISOString(),
      limit: 20,
    });
    if (!(await waitForCleanupRun(marker, queue))) {
      const startedAt = new Date();
      const cleanupRun = await prisma.cleanupRun.create({
        data: {
          jobType: 'asset-cleanup',
          status: 'running',
          startedAt,
        },
      });
      const result = await cleanupAssets({
        before: marker,
        codec: new DreamStudioSecretCodec(),
        kind: 'reference_image',
        limit: 20,
      });
      await prisma.cleanupRun.update({
        where: {
          id: cleanupRun.id,
        },
        data: {
          status: result.failedCount > 0 ? 'completed_with_errors' : 'completed',
          finishedAt: new Date(),
          scannedCount: result.scannedCount,
          deletedCount: result.deletedCount,
          failedCount: result.failedCount,
          errorSummary: result.errors.slice(0, 10).join('; ') || null,
        },
      });
    }
  } finally {
    await queue.close();
  }
}

async function waitForCleanupRun(marker: Date, queue: Queue) {
  const deadline = Date.now() + 3000;
  while (Date.now() < deadline) {
    const cleanupRun = await prisma.cleanupRun.findFirst({
      where: {
        jobType: 'asset-cleanup',
        createdAt: {
          gte: marker,
        },
      },
      orderBy: {
        createdAt: 'desc',
      },
    });
    if (cleanupRun?.finishedAt) {
      return true;
    }
    const waiting = await queue.getWaitingCount();
    if (waiting > 0) {
      // Keep polling; the worker process should pick this up when running.
    }
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  return false;
}

async function uploadReferenceImage(jar: CookieJar, buffer: Buffer) {
  const boundary = `----dreamstudio-m4-${randomBytes(8).toString('hex')}`;
  const body = Buffer.concat([
    Buffer.from(
      `--${boundary}\r\nContent-Disposition: form-data; name="file"; filename="sample.png"\r\nContent-Type: image/png\r\n\r\n`,
      'utf8',
    ),
    buffer,
    Buffer.from(`\r\n--${boundary}--\r\n`, 'utf8'),
  ]);

  return request<AssetPayload>('/api/v1/assets/reference-images', {
    method: 'POST',
    jar,
    rawBody: body,
    contentType: `multipart/form-data; boundary=${boundary}`,
  }).then((response) => response.payload);
}

async function register(username: string, password: string) {
  return request<AuthPayload>('/api/v1/auth/register', {
    method: 'POST',
    body: { username, password, display_name: username },
  });
}

async function login(username: string, password: string) {
  return request<AuthPayload>('/api/v1/auth/login', {
    method: 'POST',
    body: { username, password },
  });
}

async function get<T>(path: string, jar: CookieJar) {
  return request<T>(path, {
    method: 'GET',
    jar,
  }).then((response) => response.payload);
}

async function post<T>(path: string, jar: CookieJar, body: Record<string, unknown>) {
  return request<T>(path, {
    method: 'POST',
    jar,
    body,
  }).then((response) => response.payload);
}

async function put<T>(path: string, jar: CookieJar, body: Record<string, unknown>) {
  return request<T>(path, {
    method: 'PUT',
    jar,
    body,
  }).then((response) => response.payload);
}

async function del<T = Record<string, unknown>>(path: string, jar: CookieJar) {
  return request<T>(path, {
    method: 'DELETE',
    jar,
  }).then((response) => response.payload);
}

async function expectFailure(promise: Promise<unknown>, message: string) {
  try {
    await promise;
  } catch {
    return;
  }
  throw new Error(`Verification failed: ${message}`);
}

async function request<T>(
  path: string,
  {
    body,
    contentType,
    jar,
    method,
    rawBody,
  }: {
    method: string;
    body?: Record<string, unknown>;
    rawBody?: Buffer;
    contentType?: string;
    jar?: CookieJar;
  },
) {
  const headers: Record<string, string> = {
    accept: 'application/json',
    origin: VERIFY_ORIGIN,
  };

  if (body) {
    headers['content-type'] = 'application/json';
  }
  if (contentType) {
    headers['content-type'] = contentType;
  }
  if (jar) {
    headers.cookie = jar.cookie;
    if (!['GET', 'HEAD', 'OPTIONS'].includes(method)) {
      headers['x-csrf-token'] = jar.csrfToken;
    }
  }

  const response = await fetch(`${API_BASE_URL}${path}`, {
    method,
    headers,
    body: rawBody ? new Uint8Array(rawBody) : body ? JSON.stringify(body) : undefined,
  });
  const payload = (await response.json().catch(() => null)) as ApiEnvelope<T> | null;

  if (!response.ok || !payload?.success || payload.data === undefined) {
    throw new Error(
      `${method} ${path} failed: ${response.status} ${payload?.error?.code ?? ''} ${
        payload?.error?.message ?? ''
      }`,
    );
  }

  const setCookie = response.headers.get('set-cookie');
  return {
    payload: payload.data,
    jar:
      jar ??
      ({
        cookie: setCookie?.split(';')[0] ?? '',
        csrfToken: (payload.data as AuthPayload).csrf_token,
      } satisfies CookieJar),
  };
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) {
    throw new Error(`Verification failed: ${message}`);
  }
}

main()
  .catch((error) => {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
    await rm(LOCAL_STORAGE_ROOT, { recursive: true, force: true }).catch(() => undefined);
  });
